name: Publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
        with:
          enable-cache: true
          prune-cache: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"
      - run: make build
      - uses: sigstore/gh-action-sigstore-python@f7ad0af51a5648d09a20d00370f0a91c3bdf8f84 # v3.0.1
        with:
          inputs: |
            templates/network-${{ github.ref_name }}.yaml
            templates/data-${{ github.ref_name }}.yaml
            templates/application-${{ github.ref_name }}.yaml
      - uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            templates/network-${{ github.ref_name }}.yaml
            templates/network-${{ github.ref_name }}.yaml.sigstore.json
            templates/data-${{ github.ref_name }}.yaml
            templates/data-${{ github.ref_name }}.yaml.sigstore.json
            templates/application-${{ github.ref_name }}.yaml
            templates/application-${{ github.ref_name }}.yaml.sigstore.json
